# Generated by Django 4.2.11 on 2024-06-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0035_service_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formcategory",
            name="meta_type",
            field=models.IntegerField(
                choices=[
                    (0, "Autres"),
                    (1, "Chantier"),
                    (2, "Construction"),
                    (3, "Événement sportif"),
                    (4, "Événement culturel"),
                    (5, "Événement commercial"),
                    (6, "Dispositif de police"),
                ],
                default=0,
                help_text="Utilisé dans le calendrier afin de filtrer par type d'événement",
                verbose_name="Type générique",
            ),
        ),
    ]
