# Generated by Django 4.2.10 on 2024-04-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_service_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativeentity",
            name="agenda_name",
            field=models.CharField(
                blank=True,
                help_text="Nom utilisé afin de filtrer sur l'agenda global",
                max_length=128,
                verbose_name="Nom dans l'api agenda",
            ),
        ),
    ]
