# Generated by Django 4.2.11 on 2024-05-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_administrativeentity_agenda_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="administrativeentity",
            name="agenda_domain",
            field=models.CharField(
                blank=True,
                help_text="Utilisé afin de sélectionner les agendas visible dans agenda-embed",
                max_length=128,
                verbose_name="Domaine de l'agenda",
            ),
        ),
        migrations.AddConstraint(
            model_name="administrativeentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("agenda_domain__isnull", False)),
                fields=("agenda_domain",),
                name="unique_non_empty_agenda_domain",
            ),
        ),
    ]
