# Generated by Django 4.2.11 on 2024-06-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_administrativeentity_agenda_domain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="administrativeentity",
            name="ofs_id",
        ),
        migrations.AddField(
            model_name="administrativeentity",
            name="group_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Utilisé afin de grouper et définir l'ordre des entités.<br>Affichés par ordre croissant et groupés en cas de nombre identique",
                verbose_name="Groupe et ordre",
            ),
        ),
    ]
