# Generated by Django 4.2.11 on 2024-06-24 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_historicaluserprofile_country_userprofile_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="administrativeentity",
            name="ofs_id",
        ),
        migrations.AddField(
            model_name="administrativeentity",
            name="group_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Utilisé afin de grouper et définir l'ordre des entités.<br>Affichés par ordre croissant et groupés en cas de nombre identique",
                verbose_name="Groupe et ordre",
            ),
        ),
        migrations.AlterField(
            model_name="administrativeentity",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Seuls les chiffres et les espaces sont autorisés.",
                        regex="^(?:\\+(?:[0-9] ?){6,14}[0-9]|0\\d(?: ?\\d){8,13})$",
                    )
                ],
                verbose_name="Téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="phone_first",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Seuls les chiffres et les espaces sont autorisés.",
                        regex="^(?:\\+(?:[0-9] ?){6,14}[0-9]|0\\d(?: ?\\d){8,13})$",
                    )
                ],
                verbose_name="Téléphone principal",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="phone_second",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Seuls les chiffres et les espaces sont autorisés.",
                        regex="^(?:\\+(?:[0-9] ?){6,14}[0-9]|0\\d(?: ?\\d){8,13})$",
                    )
                ],
                verbose_name="Téléphone secondaire",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="zipcode",
            field=models.PositiveIntegerField(verbose_name="Code postal"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_first",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Seuls les chiffres et les espaces sont autorisés.",
                        regex="^(?:\\+(?:[0-9] ?){6,14}[0-9]|0\\d(?: ?\\d){8,13})$",
                    )
                ],
                verbose_name="Téléphone principal",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_second",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Seuls les chiffres et les espaces sont autorisés.",
                        regex="^(?:\\+(?:[0-9] ?){6,14}[0-9]|0\\d(?: ?\\d){8,13})$",
                    )
                ],
                verbose_name="Téléphone secondaire",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="zipcode",
            field=models.PositiveIntegerField(verbose_name="Code postal"),
        ),
    ]
