# Generated by Django 4.2.10 on 2024-04-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0028_historicalsubmission_status_agenda_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissionamendfield",
            name="is_visible_by_author",
            field=models.BooleanField(
                default=False, verbose_name="Visible par l'auteur de la demande"
            ),
        ),
    ]
