# Generated by Django 4.2.11 on 2024-04-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "submissions",
            "0029_change_default_amend_field_visibility_by_author_to_false",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicefeetype",
            name="fix_price_editable",
            field=models.BooleanField(
                default=False,
                help_text="Exemple: montant demandant un calcul spécifique à réaliser en dehors de l'application",
                verbose_name="Montant à saisir manuellement",
            ),
        ),
    ]
