# Generated by Django 4.2.11 on 2024-06-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0030_alter_servicefeetype_fix_price_editable"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubmissionvalidation",
            name="comment_is_visible_in_reports",
            field=models.BooleanField(
                default=True,
                verbose_name="Commentaire visible dans le modèle d'impression",
            ),
        ),
        migrations.AddField(
            model_name="submissionvalidation",
            name="comment_is_visible_in_reports",
            field=models.BooleanField(
                default=True,
                verbose_name="Commentaire visible dans le modèle d'impression",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubmissionvalidation",
            name="comment_is_visible_by_author",
            field=models.BooleanField(
                default=False,
                verbose_name="Commentaire visible dans le résumé pour l'auteur de la demande",
            ),
        ),
        migrations.AlterField(
            model_name="submissionvalidation",
            name="comment_is_visible_by_author",
            field=models.BooleanField(
                default=False,
                verbose_name="Commentaire visible dans le résumé pour l'auteur de la demande",
            ),
        ),
    ]
