# Generated by Django 4.2.11 on 2024-05-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0031_contact_country_historicalcontact_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="zipcode",
            field=models.PositiveIntegerField(verbose_name="Code postal"),
        ),
        migrations.AlterField(
            model_name="historicalcontact",
            name="zipcode",
            field=models.PositiveIntegerField(verbose_name="Code postal"),
        ),
    ]
